environment: "dev"
port: "8080"
debug: true
database:
  mysql:
    default: root:password@tcp(192.168.64.15:3306)/database?charset=utf8mb4,utf8&parseTime=true&loc=Local&net_read_timeout=3600&wait_timeout=3600
